name: run in docker

on: [push]

jobs:
  install_tectonic_within_container:
    runs-on: ubuntu-18.04
    container: continuumio/miniconda3:4.7.12
    steps:
      - run: which conda
      - run: conda list
      - run: conda install -c conda-forge tectonic
      - run: which tectonic
