name: run in docker

on: [push]

jobs:
  check_conda_with_uses:
    runs-on: ubuntu-18.04
    steps:
    - uses: docker://continuumio/miniconda3:4.7.12
    - run: which conda
  check_conda_without:
    runs-on: ubuntu-18.04
    steps:
    - run: which conda
